quiz_App/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testApp/', include('testApp.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^login/', include('loginPage.urls')),
    url(r'^$', include('dashboard.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "testApp"

urlpatterns = [
    url(r'^taketest/(?P<test_id>[0-9]+)$', views.StartTest.as_view(), name='index'),
    url(r'^QuestionSlide/(?P<test_id>[0-9]+)$', views.QuestionsSlide.as_view(), name='QuestionsSlide'),
    url(r'^complete_test/$', views.CompleteTest.as_view(), name='CompleteTest')
]

testApp/models.py
from django.db import models
from django.contrib.auth.models import User


class BatchTable(models.Model):
    Batch_Name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.Batch_Name


class UserExtensionTable(models.Model):
    Student = models.ForeignKey(User, null=False, on_delete='CASCADE')
    Batch = models.ForeignKey(BatchTable, null=False, on_delete='CASCADE')

    def __str__(self):
        return self.Student.username + ' - - - - - ' + self.Batch.Batch_Name


class SubjectsTable(models.Model):
    Subject_name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return self.Subject_name


class TestTable(models.Model):
    category = (
        ('Single Subject', 'Single Subject'),
        ('Multi Subject', 'Multi Subject')
    )
    Test_Name = models.CharField(max_length=250, null=False, unique=True)
    Test_category = models.CharField(max_length=250, choices=category, null=False)
    Number_of_Questions = models.IntegerField()
    Time_allotted = models.IntegerField()
    Pass_percentage = models.IntegerField(default=35)
    Test_Ready = models.BooleanField(default=False)
    Positive_mark = models.FloatField(default=1.0)
    Negative_mark = models.FloatField(default=0.25)

    def __str__(self):
        return self.Test_Name
               # + ' Test Category: ' + self.Test_category + \
               # ' number of Questions' + str(self.Number_of_Questions) + 'Time Alloted' + str(self.Time_allotted)


class TestSubjectTable(models.Model):
    Test = models.ForeignKey(TestTable, on_delete='CASCADE')
    Subject = models.ForeignKey(SubjectsTable, on_delete='CASCADE')
    sub_wise_number_of_questions = models.IntegerField()

    def __str__(self):
        return str(self.Subject.id) + self.Test.Test_Name + ' has total of ' + str(self.Test.Number_of_Questions) \
               + ' questions. in this ' + self.Subject.Subject_name + ' has '\
               + str(self.sub_wise_number_of_questions)


class TestBatchJunction(models.Model):
    Test = models.ForeignKey(TestTable, null=False, on_delete='CASCADE')
    Batch = models.ForeignKey(BatchTable, null=False, on_delete='CASCADE')

    def __str__(self):
        return self.Test.Test_Name + ' --------------- ' + self.Batch.Batch_Name


class QuestionsTable(models.Model):
    Subject = models.ForeignKey(SubjectsTable, null=False, on_delete='CASCADE')
    Question = models.TextField(max_length=500, null=False)
    Question_Image = models.ImageField(null=True, blank=True)
    Option_1 = models.CharField(max_length=500, null=False)
    Option_2 = models.CharField(max_length=500, null=False)
    Option_3 = models.CharField(max_length=500, null=False)
    Option_4 = models.CharField(max_length=500, null=False)
    choices = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
    )
    Correct_option = models.IntegerField(choices=choices)
    Solution_Explanation = models.TextField(null=False, max_length=1000)

    def __str__(self):
        return self.Subject.Subject_name + ' ---------- ' + str(self.Question)


class UserTestJunction(models.Model):
    Student = models.ForeignKey(User, null=False, on_delete='CASCADE')
    Test = models.ForeignKey(TestTable, null=False, on_delete='CASCADE')
    Status = models.CharField(max_length=200, default='inp')
    result = models.CharField(max_length=200, default='fail')

    def __str__(self):
        return self.Student.username + ' -------- ' + self.Test.Test_Name


class UserTestQuestionJunction(models.Model):
    UserTest = models.ForeignKey(UserTestJunction, on_delete='CASCADE')
    question = models.ForeignKey(QuestionsTable, on_delete='CASCADE')
    timetaken = models.IntegerField()
    option_selected = models.IntegerField()
    result = models.IntegerField()

    def __str__(self):
        return self.UserTest.Student.username + ' || ' + self.question.Question + ' || ' + str(self.result)


class BookmarksTable(models.Model):
    Student = models.ForeignKey(User, on_delete='CASCADE')
    bookmarked_question = models.ForeignKey(QuestionsTable, on_delete='CASCADE')
    doubt_description = models.TextField(null=True, max_length=1000)

testApp/views.py
from quiz_App import settings

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User
from django.db.models import Sum
import simplejson, json
from . import models
import random


class StartTest(View):
    template_name = 'testApp/index.html'

    def get(self, request, test_id):
        request.session['Test_ID'] = test_id
        test = models.TestTable.objects.get(id=test_id)
        return render(request, self.template_name, {
            'test': test
        })


class QuestionsSlide(View):
    template_name = 'testApp/QuestionSlide.html'

    def get(self, request, test_id):
        questions = []
        test = models.TestTable.objects.get(id=test_id)
        ts = models.TestSubjectTable.objects.filter(Test__id=test.id)
        ut = models.UserTestQuestionJunction.objects.filter(UserTest__Test__id=test_id)
        if ut.count() > 0:
            for u in ut:
                q = models.QuestionsTable.objects.get(id=u.question.id)
                questions.append(q)
        else:
            for subject_wise in ts:
                sub_questions = models.QuestionsTable.objects.filter(Subject=subject_wise.Subject)
                for que in sub_questions:
                    questions.append(que)
        random.shuffle(questions)
        questions = questions[0:test.Number_of_Questions]
        # questions = models.QuestionsTable.objects.filter(Test_Name=test).order_by('Subject__Subject_name')
        Data_array = []
        subject_id_array = []
        subject_array = []
        count = 0
        time_remaining = test.Time_allotted
        for question in questions:
            if question.Subject.id not in subject_id_array:
                subject_id_array.append(question.Subject.id)
                subject_array.append((question.Subject.Subject_name, count))
            count = count + 1
            question_array = []  # [q_id, q_text, q_img, op_1, op_2, op_3, op_4, selected option, Time taken, Subject Name, marked]
            question_array.append(question.id)
            question_array.append(str(question.Question))
            try:
                question_array.append(question.Question_Image.url)
            except Exception as e:
                question_array.append('')
            question_array.append(question.Option_1)
            question_array.append(question.Option_2)
            question_array.append(question.Option_3)
            question_array.append(question.Option_4)
            try:
                utqj = models.UserTestQuestionJunction.objects.get(UserTest__Test=test, UserTest__Student__username=request.user, question__id=question.id)
                question_array.append(utqj.option_selected)                            # selected option
                question_array.append(utqj.timetaken)                                  # Time taken
                time_remaining = time_remaining - utqj.timetaken
            except Exception as e:
                question_array.append(5)                            # selected option
                question_array.append(0)                            # Time taken
            question_array.append(question.Subject.Subject_name)
            try:
                if utqj.result == 4:
                    question_array.append('y')  # Marked y/n
                else:
                    question_array.append('n')
            except Exception as e:
                question_array.append('n')  # Marked y/n
            Data_array.append(question_array)
        return render(request, self.template_name, {
            'test': test,
            'Data_array': simplejson.dumps(Data_array),
            'range': range(0, len(Data_array)),
            'subject_count': ts.count(),
            'time_remaining': time_remaining,
            'subject_array': subject_array
        })


class CompleteTest(View):
    template_name = 'testApp/CompleteTest.html'

    def post(self, request):
        Data_array = json.loads(request.POST['json_container'])
        user = User.objects.get(username=request.user)
        test = models.TestTable.objects.get(id=request.session['Test_ID'])
        try:
            # If entries are already present (Resume test scenario)
            utj = models.UserTestJunction.objects.get(Student=user, Test=test)
            for row in Data_array:
                utqj = models.UserTestQuestionJunction.objects.get(UserTest=utj, question__id=row[0])
                utqj.timetaken = row[8]
                utqj.option_selected = row[7]
                if int(utqj.question.Correct_option) == int(utqj.option_selected):
                    utqj.result = 1 # code for correct answer
                else:
                    if int(utqj.option_selected) > 4:
                        utqj.result = 2   #code for unanswered Questions
                    else:
                        utqj.result = 3  # code for wrong answer
                    if row[10] == 'y' or row[10] == 'yy':
                        utqj.result = 4  # code for marked Questions
                utqj.save()
        except Exception as e:
            # The entries are added for the first time
            utj = models.UserTestJunction(Student=user, Test=test)
            utj.save()
            for row in Data_array:
                utqj = models.UserTestQuestionJunction(UserTest=utj)
                utqj.question = models.QuestionsTable.objects.get(id=row[0])
                utqj.timetaken = row[8]
                utqj.option_selected = row[7]
                if int(utqj.question.Correct_option) == int(utqj.option_selected):
                    utqj.result = 1 # code for correct answer
                else:
                    if int(utqj.option_selected) > 4:
                        utqj.result = 2   #code for unanswered Questions
                    else:
                        utqj.result = 3  # code for wrong answer
                utqj.save()
        try:
            if request.POST['complete_test'] == 'on':
                utqj = models.UserTestQuestionJunction.objects.filter(UserTest=utj)
                utj.Status = 'completed'
                Total_questions = test.Number_of_Questions
                Total_marks = Total_questions*test.Positive_mark
                no_of_correct_answer = utqj.filter(result=1).count()
                no_of_unanswered_answer = utqj.filter(result=2).count()
                no_of_wrong_answer = utqj.filter(result=3).count()
                total_time_taken = utqj.aggregate(Sum('timetaken'))
                obtained_marks = (no_of_correct_answer*test.Positive_mark)-(no_of_wrong_answer*test.Negative_mark)
                user_percentage = obtained_marks/Total_marks * 100
                required_marks = test.Pass_percentage
                # to calculate subject wise data
                subject_wise_marks = []
                subject_array = set(utqj.values_list('question__Subject', flat=True))
                for subject_id in subject_array:
                    subject_data = utqj.filter(question__Subject=subject_id)
                    subject_wise_marks.append((models.SubjectsTable.objects.get(id=subject_id),
                                              subject_data.filter(result=1).count()*test.Positive_mark,
                                              subject_data.filter(result=1).count(),
                                              subject_data.filter(result=3).count(),
                                              subject_data.aggregate(Sum('timetaken')),
                                               ))
                if user_percentage > required_marks:
                    utj.result = 'pass'
                else:
                    utj.result = 'fail'
                utj.save()
                return render(request, self.template_name, {
                    'total_marks_obtained': obtained_marks,
                    'total_time_taken': total_time_taken,
                    'subject_wise_marks': subject_wise_marks,
                    'obtained_percentage': user_percentage,
                    'wrong_marks': no_of_wrong_answer*test.Negative_mark,
                    'Total_marks': Total_marks,
                    'obtained_marks': obtained_marks
                })
        except Exception as e:
            return render(request, 'testApp/close_js.html')

testApp/templates/testApp/CompleteTest.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="icon" type="image/png" href="images/icons/favicon1.ico"/>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
    .table{
    margin-top:12px;
    border: solid;
    }

    .btn-primary {
        display: inline-block;
        padding: 9px 9px;
        margin-bottom: 0;
        padding-right: 17px;
        margin-right: 8px;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;

        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
    height:40px;
    width:40px;
    }

    .sidenav {
        padding-top: 20px;
        background-color: #f1f1f1;
        height: auto;
    }
    </style>
</head>
<body>



<div class="container-fluid text-center">

<div class="col-sm-12 sidenav">
  <div class="well">
      <table style="width: 100%">
          <tr>
              <td><div id="chart_div_1"></div></td>
              <td><div id="chart_div_2"></div></td>
          </tr>
      </table>
  </div>
</div>
  <div class="row content">

    <div class="col-sm-12 text-left">
      <div class="summary">
	  <h5>Total Test Score: {{ total_marks_obtained }}</h5>
	  <hr>
	 <h5>Total Time Taken: {{ total_time_taken.timetaken__sum }}</h5>
	  <hr>
	<h5>Subject Wise Marks:</h5>

<table class="table">

<thead>
<tr>
<th>Subject Name</th>
<th>Marks Obtained</th>
<th>Total Right</th>
<th>Total Wrong</th>
<th>Time Taken</th>
</tr>
</thead>
<tbody>
{% for subject in subject_wise_marks %}
    <tr>
        <td>{{ subject.0 }}</td>
        <td>{{ subject.1 }}</td>
        <td>{{ subject.2 }}</td>
        <td>{{ subject.3 }}</td>
        <td>{{ subject.4.timetaken__sum }}</td>
    </tr>
{% endfor %}
</tbody>
</table>
</div>

</div>
<h3 style="background: orange">You Got: {{ obtained_marks }} out of {{ Total_marks }}</h3>

</div>
</div>
</body>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
        google.charts.load('current', {packages: ['corechart']});
        google.charts.setOnLoadCallback(initChart);
        function initChart() {
            // initialization of graphs
            data_1 = [
              ['Subject', 'marks'],
              ['Total wrong', {{ wrong_marks }}]
            ];
            data_2 = [['Question', 'Time Taken']];

            {% for subject in subject_wise_marks %}
                data_1.push(['{{ subject.0 }}', {{ subject.1 }}]);
                data_2.push(['{{ subject.0 }}', {{ subject.4.timetaken__sum }}]);
            {% endfor %}

            data_1 = google.visualization.arrayToDataTable(data_1);
            data_2 = google.visualization.arrayToDataTable(data_2);

            Chart_1 = new google.visualization.PieChart(document.getElementById('chart_div_1'));
            Chart_1.draw(data_1, {'title': 'Marks Obtained Graph'});

            Chart_2 = new google.visualization.PieChart(document.getElementById('chart_div_2'));
            Chart_2.draw(data_2, {'title': 'Time per subject Graph'});
          };

</script>
</html>

testApp/templates/testApp/close_js.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    window.close();
</script>
</body>
</html>

testApp/templates/testApp/index.html
<!---------Instruction Page-------------->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{ test.Test_Name }}</title>
    {% load static %}
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
	  function toggle_submit(){
	  	if(document.getElementById('submit_button').disabled){
	  		document.getElementById('submit_button').disabled = false;
	  	}
	  	else{
	  		document.getElementById('submit_button').disabled = true;
	  	}
	  }
  </script>
	<link rel="icon" type="image/png" href="images/icons/favicon1.ico"/>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
</head>
<body>



<div class="container-fluid text-center">
  <div class="row content">

    <div class="col-sm-9 text-left">
      <h1>{{ test.Test_Name }}</h1>
      <hr>

   <div class="lt-container main-container">


    						<div class="col-md-12 tl-main">
    							<div class="tl-page1 ">
    								<div class="tl-content" style="height: 781px;">
    									<div id="instEN" class="" style="height: 98.9%; width: 100%; overflow: auto;"><p align="center"><strong><span><b>Please read the following instructions carefully</b></span></strong></p>
											<p><strong><u>General Instructions:</u></strong> <br></p>
											<ol>
											<li>Total of 30 minutes duration will be given to attempt all the questions</li>
											<li>The clock has been set at the server and the countdown timer at the top right corner of your screen will display the time remaining for you to complete the exam. When the clock runs out the exam ends by default - you are not required to end or submit your exam. </li>
											<li>The question palette at the right of screen shows one of the following statuses of each of the questions numbered:
											<table>
											<tbody>
											<tr>
											<td valign="top" class="btn-in-inst btn_nv"><button class="button1 button1"></button></td>
											<td>You have answered the question.</td></tr></tbody></table>
											<table>
											<tbody>
											<tr>
											<td valign="top" class="btn-in-inst btn_na"><button class="button2 button1"></button></td>
											<td>You have not answered the question.</td></tr></tbody></table>
											<table>
											<tbody>
											<tr>
											<td valign="top" class="btn-in-inst btn_a"><button class="button3 button1"></button></td>
											<td>You have NOT answered the question but have marked the question for review. </td></tr></tbody></table>
											<table>
											<tbody>
											<tr>
											<td valign="top" class="btn-in-inst btn_m"><button class="button4 button1"></button></td>
											<td>You have NOT visited the question yet.</td></tr></tbody></table>
											<!--<table>
											<tbody>
											<tr>
											<td valign="top" class="btn-in-inst btn_ma"><button id="tooltip_reviewanswered">9</button></td>
											<td>You have answered the question but marked it for review. </td></tr></tbody></table>-->
											</li>
											<li style="LIST-STYLE-TYPE: none">The Marked for Review status simply acts as a reminder that you have set to look at the question again. <font color="red"><i>If an answer is selected for a question that is Marked for Review, the answer will be considered in the final evaluation.</i></font></li></ol>
											<p><br><b><u>Navigating to a question : </u></b></p>
											<ol start="4">
											<li>To select a question to answer, you can do one of the following:
											<ol type="a">
											<li>Click on the question number on the question palette at the right of your screen to go to that numbered question directly. Note that using this option does NOT save your answer to the current question. </li>
											<li>Click on Save and Next to save answer to current question and to go to the next question in sequence.</li>
											<li>Click on Mark for Review and Next to save answer to current question, mark it for review, and to go to the next question in sequence.</li></ol></li>
											<li>You can view the entire paper by clicking on the <b>Question Paper</b> button.</li></ol>
											<p><br><b><u>Answering questions : </u></b></p>
											<ol start="6">
											<li>For multiple choice type question :
											<ol type="a">
											<li>To select your answer, click on one of the option buttons</li>
											<li>To change your answer, click the another desired option button</li>
											<li>To save your answer, you MUST click on <b>Save &amp; Next</b> </li>
											<li>To deselect a chosen answer, click on the chosen option again or click on the <b>Clear Response</b> button.</li>
											<li>To mark a question for review click on <b>Mark for Review &amp; Next</b>. <font color="red"><i>If an answer is selected for a question that is Marked for Review, the answer will be considered in the final evaluation. </i></font></li></ol></li>
											<li>To change an answer to a question, first select the question and then click on the new answer option followed by a click on the <b>Save &amp; Next</b> button.</li>
											<li>Questions that are saved or marked for review after answering will ONLY be considered for evaluation.</li></ol>
											<p><br><b><u>Navigating through sections : </u></b></p>
											<ol start="9">
											<li>Sections in this question paper are displayed on the top bar of the screen. Questions in a section can be viewed by clicking on the section name. The section you are currently viewing is highlighted.</li>
											<li>After clicking the <b>Save &amp; Next</b> button on the last question for a section, you will automatically be taken to the first question of the next section. </li>
											<li>You can move the mouse cursor over the section names to view the status of the questions for that section. </li>
											<li>You can shuffle between sections and questions anytime during the examination as per your convenience. </li></ol>
										</div>


 </div>
</div>
<hr>
<form method="get" action="{% url 'testApp:QuestionsSlide' test.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-info" id="submit_button" disabled>Start Exam</button>
</form>
<div class="col-sm-9 col-md-6 col-lg-10">
<p>
<form>
  <input type="checkbox" id="tandc" onclick="toggle_submit()">
  <span class="inst">I have read and understood the instructions. All Computer Hardwares allotted to me are in proper working condition. I agree that I am not carrying any prohibited gadget like mobile phone etc. / any prohibited material with me into the exam hall.  I agree that in case of not adhering to the instructions, I will be disqualified from taking the exam.</span>
</form>
</p>


</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body>


<style>



.btn-primary {
    display: inline-block;
    padding: 9px 9px;
    margin-bottom: 0;
    padding-right: 17px;
    margin-right: 8px;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;

    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
height:40px;
width:40px;
}

.sidenav {
    padding-top: 20px;
    background-color: #f1f1f1;
    height: auto;
}

.inst{

color:red;
}
</style>
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/test.css' %}">
</html>