dashboard/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
app_name = 'dashboard'

urlpatterns = [
    url(r'^homepage/$', login_required(views.HomePageView.as_view()), name='homepage'),
    url(r'^mytests/$', login_required(views.MyTestView.as_view()), name='mytests'),
    url(r'^testquestions/(?P<test_id>[0-9]+)/$', login_required(views.TestQuestionsView.as_view()), name='testquestions'),
    url(r'^bookmark/(?P<test_id>[0-9]+)/$', login_required(views.AddBookmarkView.as_view()), name='addbookmark'),
    url(r'^bookmark/remove/(?P<question_id>[0-9]+)/$', login_required(views.RemoveBookmarkView.as_view()), name='removebookmark'),
    url(r'^bookmark/list/$', login_required(views.BookMarkListView.as_view()), name='bookmarklist'),
    url(r'^profile/$', login_required(views.ProfileView.as_view()), name='profile'),
    url(r'^custom_admin/$', login_required(views.CustomAdmin.as_view()), name='CustomAdmin'),
    url(r'^$', views.AboutUs.as_view(), name='about_us'),
]

loginPage/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
app_name = "login_App"


urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='index'),
    url(r'^logout/$',  views.logoutview, name='logout'),
]

quiz_App/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testApp/', include('testApp.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^login/', include('loginPage.urls')),
    url(r'^$', include('dashboard.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "testApp"

urlpatterns = [
    url(r'^taketest/(?P<test_id>[0-9]+)$', views.StartTest.as_view(), name='index'),
    url(r'^QuestionSlide/(?P<test_id>[0-9]+)$', views.QuestionsSlide.as_view(), name='QuestionsSlide'),
    url(r'^complete_test/$', views.CompleteTest.as_view(), name='CompleteTest')
]

dashboard/models.py
from django.db import models

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User
from testApp import models


class HomePageView(View):
    template_name = 'dashboard/HomePage.html'

    def get(self, request):
        user_object = User.objects.get(username=request.user)
        test_status_string = None
        testbatch = None
        if user_object.is_staff:
            all_tests = models.TestTable.objects.all()
            test_status_string = self.check_status(all_tests)
            is_admin = True
        else:
            batch_object = models.UserExtensionTable.objects.filter(Student=user_object)
            testbatch = []
            for batch in batch_object:
                testbatch_1 = models.TestBatchJunction.objects.filter(Batch=batch.Batch, Test__Test_Ready=True)
                for tb in testbatch_1:
                    if not models.UserTestJunction.objects.filter(Test=tb.Test, Student=user_object):
                        testbatch.append(tb)
            is_admin = False
        return render(request, self.template_name, {
                        'testbatch': testbatch,
                        'is_admin': is_admin,
                        'test_status_string': test_status_string
        })

    def post(self, request):
        return HomePageView.get(self, request)

    def check_status(self, all_tests):
        test_status_string = []  # (Test name , Status Description, Status )
        for test in all_tests:
            test_mini_string = []
            all_test_subjects = models.TestSubjectTable.objects.filter(Test=test)
            test_mini_string.append(test.Test_Name)
            status_fail = False
            status_string = ''
            has_data = False
            for ts in all_test_subjects:
                has_data =True
                required_count = ts.sub_wise_number_of_questions
                available_count = models.QuestionsTable.objects.filter(Subject=ts.Subject).count()
                status_string = status_string + ts.Subject.Subject_name + ' : ' + str(available_count) \
                                + '/' + str(required_count) + ' '
                if not required_count <= available_count:
                    status_fail = True
            if not has_data:
                status_string = 'You havent added Subject wise Split Up'
                status_fail = True
            test_mini_string.append(status_string)
            if status_fail:
                test_mini_string.append('Test Not Ready')
            else:
                test_mini_string.append('Test Ready')
            test_status_string.append(test_mini_string)
        return test_status_string


class MyTestView(View):

    def get(self, request):
        user = User.objects.get(username=request.user)
        all_taken_tests = models.UserTestJunction.objects.filter(Student=user)
        print(all_taken_tests)
        return render(request, 'dashboard/mytests.html', {
            'all_tests': all_taken_tests
        })


class TestQuestionsView(View):

    def get(self, request, test_id):
        test = models.TestTable.objects.get(id=test_id)
        user = User.objects.get(username=request.user)
        utj = models.UserTestJunction.objects.get(Student=user, Test=test)
        utqj = models.UserTestQuestionJunction.objects.filter(UserTest=utj)
        bookmarks = models.BookmarksTable.objects.filter(Student=user)
        bookmark_list = []
        for bookmark in bookmarks:
            bookmark_list.append(bookmark.bookmarked_question.id)
        total_time_spent = 0
        subject_wise_array = []
        for question in utqj:
            total_time_spent = total_time_spent + question.timetaken
        subject_list = set(utqj.values_list('question__Subject', flat=True))
        for sub_id in subject_list:
            subject = models.SubjectsTable.objects.get(id=sub_id)
            query = models.UserTestQuestionJunction.objects.filter(question__Subject=subject)
            total_number_of_subject_questions = query.count()
            correct_number_of_subject_questions = query.filter(result=1).count()
            incorrect_number_of_subject_questions = query.filter(result=3).count()
            positive_marks = correct_number_of_subject_questions*test.Positive_mark
            negative_marks = incorrect_number_of_subject_questions*test.Negative_mark
            subject_wise_array.append([subject.Subject_name,
                                       total_number_of_subject_questions,
                                       correct_number_of_subject_questions,
                                       incorrect_number_of_subject_questions,
                                       positive_marks,
                                       negative_marks,
                                       positive_marks-negative_marks
                                       ])
        #    subject_wise_array.append([subject.Subject_name, subject])
        Total_marks = test.Number_of_Questions*test.Positive_mark
        no_of_correct_answer = utqj.filter(result=1).count()
        no_of_unanswered_answer = utqj.filter(result=2).count()
        no_of_wrong_answer = utqj.filter(result=3).count()
        obtained_marks = (no_of_correct_answer * test.Positive_mark) - (no_of_wrong_answer * test.Negative_mark)
        return render(request, 'dashboard/testquestions.html', {
            'all_questions_utqj': utqj,
            'test_id': test_id,
            'bookmark_list': bookmark_list,
            'Total_marks': Total_marks,
            'Total_time': test.Time_allotted/60,
            'Total_questions': test.Number_of_Questions,
            'user_marks': obtained_marks,
            'total_time_spent_min': int(total_time_spent/60),
            'total_time_spent_sec': int(total_time_spent % 60),
            'Total_correct': no_of_correct_answer,
            'Total_incorrect': no_of_wrong_answer,
            'Total_unanswered': no_of_unanswered_answer,
            'percentage_scored': obtained_marks/Total_marks*100,
            'subject_wise_array': subject_wise_array
        })


class AddBookmarkView(View):

    def get(self, request, test_id):
        user = User.objects.get(username=request.user)
        bookmark = models.BookmarksTable()
        bookmark.Student = user
        question = models.QuestionsTable.objects.get(id=int(request.GET['question_id']))
        bookmark.bookmarked_question = question
        try:
            bookmark.doubt_description = self.request.GET['doubt_description']
        except Exception as e:
            bookmark.doubt_description = ''
        bookmark.save()
        return redirect('dashboard:testquestions', test_id)


class RemoveBookmarkView(View):

    def get(self, request, question_id):
        models.BookmarksTable.objects.get(id=question_id).delete()
        return redirect('dashboard:bookmarklist')


class BookMarkListView(View):

    def get(self, request):
        user = User.objects.get(username=request.user)
        Data_array = []
        bookmarks = models.BookmarksTable.objects.filter(Student=user)
        Data_array.append(['All Questions', bookmarks])
        subject_id_list = set(bookmarks.values_list('bookmarked_question__Subject__id', flat=True))
        for ids in subject_id_list:
            print('here')
            bookmarks_array = bookmarks.filter(bookmarked_question__Subject__id=ids)
            subject_name = bookmarks_array[0].bookmarked_question.Subject.Subject_name
            Data_array.append([subject_name, bookmarks_array])
        return render(request, 'dashboard/bookmarkslist.html', {
            'Data_array': Data_array
        })


class ProfileView(View):

    def get(self, request):
        user = models.User.objects.get(username=request.user)
        batch_list = models.UserExtensionTable.objects.filter(Student=user)
        return render(request, 'dashboard/profile.html', {
            'user': user,
            'batch_list': batch_list
        })


class AboutUs(View):

    def get(self, request):
        return render(request, 'dashboard/aboutus.html')


class CustomAdmin(View):

    def get(self, request):
        student_list = models.User.objects.filter()
        batch_list = models.BatchTable.objects.filter()
        return render(request, 'dashboard/custom_admin.html', {
                    'student_list': student_list,
                    'batch_list': batch_list,
                    'msg': ''
        })

    def post(self, request):
        batch = models.BatchTable.objects.get(id=int(request.POST['batch']))
        for student_id in request.POST.getlist('student_list'):
            user = models.User.objects.get(id=int(student_id))
            models.UserExtensionTable(Student=user, Batch=batch).save()
        student_list = models.User.objects.filter()
        batch_list = models.BatchTable.objects.filter()
        return render(request, 'dashboard/custom_admin.html', {
            'student_list': student_list,
            'batch_list': batch_list,
            'msg': 'successfully added!!'
        })

dashboard/templates/dashboard/HomePage.html
{% extends 'dashboard/base.html' %}
{% block pagecontent %}
{% load static %}
{% load staticfiles %}
    <!--------- DASHBOARD ICONS-------------->
    <div class="dashIcons">
 <div class="row">
     <div></div>
      <!-- edit form column -->
      <div class="col-md-9 personal-info">
        <div class="col-md-12 pd0">
                <div class="col-md-3">
                    <div class="col-md-5">
                            <img src="{% static 'dashboard/images/scores.jpg' %}" alt="Smiley face" height="100" width="100" style="margin-top:100px;">
                         <div class="col-md-7">
                           <b>Goal</b>
                         </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="col-md-5">

                        <img src="{% static 'dashboard/images/reporting-icon.png' %}" alt="Smiley face" height="110" width="110" style="margin-top:100px;">
                        <div class="col-md-7">
                            <b>Tests</b>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="col-md-5">
                        <img src="{% static 'dashboard/images/progress-icon.png' %}" alt="Smiley face" height="100" width="100" style="margin-top:100px;">
                        <div class="col-md-7">
                            <b>Progress</b>
                        </div>
                    </div>
                </div>


                <div class="col-md-3">
                    <div class="col-md-5">
                            <img src="{% static 'dashboard/images/completed.png' %}" alt="Smiley face" height="100" width="100" style="margin-top:100px;">
                        <div class="col-md-7">
                            <b>Status</b>
                        </div>
                    </div>
                </div>
        </div>
	</div>


 <!---------TABLE CONTAINER DIV --------->

{% if is_admin %}
     <div class="container-table100">
	 <div class="wrap-table100">
                <div class="table100 ver1 m-b-110">
                    <div class="table100-head">
                        <table>
                            <thead>
                                <tr class="row100 head">
                                    <th class="cell100 column1">sl no</th>
                                    <th class="cell100 column2">Test Name</th>
                                    <th class="cell100 column3">Status Description</th>
                                    <th class="cell100 column4">Status</th>
                                </tr>
                            </thead>
                        </table>
                    </div>

                    <div class="table100-body js-pscroll">
                        <table>
                            <tbody>
                                {% for string in test_status_string %}
                                <tr class="row100 body">
                                    <td class="cell100 column1">{{ forloop.counter }}</td>
                                    <td class="cell100 column2">{{ string.0 }}</td>
                                    <td class="cell100 column3">{{ string.1 }}</td>
                                    <td class="cell100 column4">{{ string.2 }}</td>
                                </tr>
                            {% endfor %}
                            <tr class="row100 body">
                                <td class="cell100 column1">
                                    <a href="{% url 'dashboard:CustomAdmin' %}" style="color: black" class="btn btn-primary">Assign Batches to users</a>
                                </td>
                            </tr>
                              </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
{% else %}
     <div class="container-table100">
	 <div class="wrap-table100">
                <div class="table100 ver1 m-b-110">
                    <div class="table100-head">
                        <table>
                            <thead>
                                <tr class="row100 head">
                                    <th class="cell100 column1">Test No.</th>
                                    <th class="cell100 column2">Course Name</th>
                                    <th class="cell100 column3">Pass Percentage</th>
                                    <th class="cell100 column4">Action</th>

                                </tr>
                            </thead>
                        </table>
                    </div>

                    <div class="table100-body js-pscroll">
                        <table>
                            <tbody>
                            {% if testbatch %}
                                {% for tb in testbatch %}
                                    <tr class="row100 body">
                                        <td class="cell100 column1">{{ tb.Test.id }}</td>
                                        <td class="cell100 column2">{{ tb.Test.Test_Name }}</td>
                                        <td class="cell100 column3">{{ tb.Test.Pass_percentage }} %</td>
                                        <td class="cell100 column4">
                                            <form>
                                                <a href="{% url 'testApp:index' tb.Test.id %}" target="_blank"
                                           onclick="window.open(this.href,'width=640, height=screen.height, menubar=no')">
                                                <button type=button style="width:75%" class="btn btn-default">
                                                        Start Test
                                                </button>
                                                </a>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr class="row100 body">
                                    <td class="cell100 column1">No Tests Available</td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
{% endif %}

    </div>
 </div>
{% endblock %}

dashboard/templates/dashboard/base.html
<!-----------Dashboard It is the First Page to be Displayed aafter Login In------->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=2.0">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% load static %}
    {% load staticfiles %}
<!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'dashboard/images/icons/favicon1.ico' %}"/>
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <meta http-equiv="X-UA-Compatible" content="IE=edge">


         <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>

	                         <!---SIDEBAR COMPONENTS----->

    <body>
 <div class="wrapper">

            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3>SHAKSHIN Welcomes You!</h3>
                    <strong></strong>
                </div>

                <ul class="list-unstyled components">
                    <li>
                        <a href="{% url 'dashboard:profile' %}">
                            <i class="glyphicon glyphicon-user"></i>
                            My Profile
                        </a>
                    </li>
					<li>
					<a href="{% url 'dashboard:homepage'  %}">
                            <i class="glyphicon glyphicon-stats"></i>
                            Dashboard
                    </a>
					</li>
					<li>
                        <a href="{% url 'dashboard:mytests' %}">
                            <i class="glyphicon glyphicon-pencil"></i>
                            My Test
                        </a>

                        <ul class="collapse list-unstyled">

                        </ul>
                    </li>
               <!-- <li>
                        <a href="#" onclick="alert('Coming Soon');">
                            <i class="glyphicon glyphicon-th"></i>
                            My Result
                        </a>
                    </li>   -->
                    <li>
                        <a href="{% url 'dashboard:bookmarklist' %}">
                            <i class="glyphicon glyphicon-star"></i>
                           My Bookmarks
                        </a>
                    </li>
                 </ul>
			</nav>

            <!-- Page Content Holder -->
<div id="content">



                <!----TOP NAVIGATION BAR---------->

<div class="navbar" style="background-image: url('{% static 'dashboard/images/sakshim.jpg' %}');">
         <div class="container">
	       <div class="row">
		     <div class="dropdown">
      <ul>
         <li>
          {{ request.user }} <i class="fa fa-sort-desc" aria-hidden="true"></i>
        <ul>
		  </li>
            <li><a href="{% url 'dashboard:profile' %}" style="display:block; margin: 0px; padding: 0px; width: 100%; height: 100%;">
                Account Setting</a></li>
		    <li><a href="{% url 'login_App:logout' %}" style="display:block; margin: 0px; padding: 0px; width: 100%; height: 100%;">
                Logout</a></li>
        </ul>
         <li><a href="{% url 'dashboard:homepage'  %}" style="display:block; margin: 0px; padding: 0px; width: 100%; height: 100%;">
          Home</a></li>
		<li><a href="{% url 'dashboard:about_us' %}" style="display:block; margin: 0px; padding: 0px; height: 100%;">
            About Us</a></li>
      </ul>
    </div>
	</div>
	</div>
 </div>
 {% block pagecontent %}
 {% endblock %}


<script>


    $(document).ready(function () {

    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
    });

});
</script>



<script src="{% static 'dashboard/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'dashboard/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'dashboard/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'dashboard/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script>
        $('.js-pscroll').each(function(){
            var ps = new PerfectScrollbar(this);

            $(window).on('resize', function(){
                ps.update();
            })
        });
    </script>
<!--===============================================================================================-->
    <script src="{% static 'dashboard/js/main.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/mainstyle.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/header.css' %}">
{% block script %}
{% endblock %}
</div>
 </div>
    </body>
</html>

dashboard/templates/dashboard/custom_admin.html
<h2>ADD many users to a Batch</h2>
<p>{{ msg }}</p>
<form action="{% url 'dashboard:CustomAdmin' %}" method="post">
    {% csrf_token %}
    <select name="batch">
        {% for batch in batch_list %}
            <option value="{{ batch.id }}">{{ batch.Batch_Name }}</option>
        {% endfor %}
    </select>
    <button type="submit">Submit</button><br>
    <h3>Student List</h3>
        {% for student in student_list %}
                <input type="checkbox" name="student_list" value="{{ student.id }}">{{ student.username }}<br>
        {% endfor %}
</form>

dashboard/templates/dashboard/mytests.html
{% extends 'dashboard/base.html' %}
{% block pagecontent %}
    {% load static %}
    {% load staticfiles %}
     <div class="limiter">
        <div class="container-table100">
            <div class="wrap-table100">
                <div class="table100 ver1 m-b-110">
                    <div class="table100-head">
                        <table>
                            <thead>
                                <tr class="row100 head">
                                    <th class="cell100 column1">ExamId</th>
                                    <th class="cell100 column2">Exam Name</th>
                                    <th class="cell100 column3">Duration</th>
                                    <th class="cell100 column4">Question</th>

                                </tr>
                            </thead>
                        </table>
                    </div>

                    <div class="table100-body js-pscroll">
                        <table>
                            <tbody>
                                {% if all_tests %}
                                    {% for test in all_tests %}
                                        <tr class="row100 body">
                                            <td class="cell100 column1">{{ forloop.counter }}</td>
                                            <td class="cell100 column2">{{ test.Test.Test_Name }}</td>
                                            <td class="cell100 column3">
                                                {% if test.result == 'pass' %}
                                                    Solved
                                                {% else %}
                                                    {% if test.Status == 'completed' %}
                                                        Attempted (failed)
                                                    {% else %}
                                                        Paused
                                                    {% endif %}
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if test.Status == 'completed' %}
                                                    <form method="get" action="{% url 'dashboard:testquestions' test.Test.id %}">
                                                        <button type="submit" class="btn btn-success">View Report</button>
                                                    </form>
                                                {% else %}
                                                    <a href="{% url 'testApp:index' test.Test.id %}" target="_blank" onclick="window.open(this.href, '_blank','width=640, height=screen.height, menubar=no')">
                                                        <button type=button style="width:75%" class="btn btn-success">
                                                                Resume Test
                                                        </button>
                                                    </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr class="row100 body">
                                        <td class="cell100 column1">No Tests Available</td>
                                    </tr>
                                {% endif %}
                             </tbody>
                         </table>
                     </div>
                  </div>
              </div>
          </div>
      </div>
{% endblock %}